# : Manager [[[

[mgr]
cwd = { fg = "#e2e2e2" }

# Tab
tab_active = { fg = "#242478", bg = "#c1c1ff", bold = true }
tab_inactive = { fg = "#3b3d8f", bg = "#e1e0ff" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5f3c51", bg = "#5f3c51" }
marker_cut = { fg = "#5f3c51", bg = "#5f3c51" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e9b9d3", bg = "#e9b9d3" }

# Count
count_copied = { fg = "#ffd8ec", bg = "#5f3c51" }
count_cut = { fg = "#ffd8ec", bg = "#5f3c51" }
count_selected = { fg = "#242478", bg = "#e9b9d3" }

# Border
border_style  = { fg = "#c1c1ff" }

# : ]]]


# : Status [[[

[status]
separator_style = { bg = "#242478", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c1c1ff", fg = "#242478", bold = true }
normal_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Select mode
select_main = { bg = "#c6c4dd", fg = "#2e2f42", bold = true }
select_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Unset mode
unset_main = { bg = "#e9b9d3", fg = "#46263a", bold = true }
unset_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c1c1ff", bg = "#131313" }
progress_error = { fg = "#ffb4ab", bg = "#131313" }

# Permissions
permissions_t = { fg = "#c6c4dd" }
permissions_w = { fg = "#e9b9d3" }
permissions_x = { fg = "#ffb4ab" }
permissions_r = { fg = "#5f3c51" }
permissions_s = { fg = "#3b3d8f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c1c1ff" }
active = { fg = "#e9b9d3", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#c1c1ff" }
value = { fg = "#e2e2e2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#c1c1ff", bold = true, bg = "#131313" }
inactive = { fg = "#c6c4dd", bg = "#131313" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c1c1ff", bg = "#242478" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c1c1ff" }
title = {}
hovered = { fg = "#5f3c51", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#131313" }
cand = { fg = "#c1c1ff" }
rest = { fg = "#242478" }
desc = { fg = "#e2e2e2" }
separator = " ▶ "
separator_style = { fg = "#e2e2e2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e2e2" }
run = { fg = "#e2e2e2" }
footer = { fg = "#2e2f42", bg = "#c6c4dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e9b9d3" }
title_warn = { fg = "#c1c1ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e2e2e2" },
    { name = "*/", fg = "#c1c1ff" },
]

# : ]]]
